name: spectr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #intl: ^0.17.0
  flutter_lints: ^1.0.4
  provider: ^6.0.0
  json_annotation: ^4.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.2
  intl_phone_number_input: ^0.7.3+1
  country_code_picker: ^3.0.0
  camera: ^0.10.5+2
  flutter_ffmpeg: ^0.4.2
  flag: ^7.0.0
  pin_code_fields: ^8.0.1
  permission_handler: ^10.4.1
  video_player: ^2.7.0
  gallery_saver: ^2.3.2
  #spider: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4
  build_runner: ^2.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  assets:
    # - assets/images/1.5x/Mask_group.png
    # - assets/images/1.5x/Profile.png
    # - assets/images/1.5x/Union.png
    # - assets/images/2x/Mask_group.png
    # - assets/images/2x/Profile.png
    # - assets/images/2x/Union.png
    # - assets/images/3x/Mask_group.png
    # - assets/images/3x/Profile.png
    # - assets/images/3x/Union.png
    # - assets/images/4x/Mask_group.png
    # - assets/images/4x/Profile.png
    # - assets/images/4x/Union.png
    - assets/images/Mask_group.png
    - assets/images/Profile.png
    - assets/images/Union.png
    - assets/images/Logo.png
    
  fonts:
    - family: seoulnamsan
      fonts:
        - asset: assets/fonts/seoulnamsan-cbl.ttf
          weight: 400 
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
          weight: 400  